package com.example.warehousemanagerapp.util

object JsonConst {
    const val WAREHOUSE_ID = "id"
    const val NAME = "name"
    const val PASSWORD = "password"
    const val ADDRESS = "address"
    const val COLOR = "color"
    const val IMAGE = "image"
    const val ADDRESS_ID = "id"
    const val STREET_NAME = "street_name"
    const val HOUSE_NUMBER = "house_number"
    const val LOCAL_NUMBER = "local_number"
    const val PLACE = "place"
    const val CODE = "code"
    const val OWNER_NAME = "name"
    const val EMAIL = "email"
    const val OWNER = "owner"
    const val OWNER_ID = "id"
    const val CONTRACTORS = "contractors"
    const val CONTRACTOR_ID = "id"
    const val CONTRACTOR_NAME = "name"
    const val CONTRACTOR_ADDRESS = "address"
    const val RECIPIENT = "recipient"
    const val SUPPLIER = "supplier"
    const val NIP = "nip"
    const val COMMODITIES = "commodities"
    const val COMMODITIES_ID = "id"
    const val COMMODITIES_NAME = "name"
    const val COUNTER = "counter"
    const val TEMP_COUNTER = "temp_counter"
    const val DESCRIPTION = "description"
    const val EXPIRATION_DATE = "expiration_date"
    const val UNIT = "unit"
    const val ORDERS = "orders"
    const val ORDER_ID = "id"
    const val SUBMIT_TIME = "submit_time"
    const val ACCEPT_TIME = "accept_time"
    const val COMPLETED_TIME = "completed_time"
    const val ORDER_STATUS = "order_status"
    const val CONTRACTOR = "contractor"
    const val COMMODITIES_LIST = "commodities_list"
    const val STORE_ACTIONS = "store_actions"
    const val STORE_ACTION_DATE = "date"
    const val STORE_ACTION_ID = "id"
    const val DOC_NUMBER = "doc_number"
}